# Change baseurl before deploy
baseurl = "https://129700.github.io/"
publishDir = "docs"
locale  = "zh-cn"
title   = "129700 的笔记站"

# Theme i18n support
defaultContentLanguage = "zh-cn"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
hasCJKLanguage = true

# Disable disqus
disqusShortname = ""

[pagination]
    pagerSize = 5