# Configure main menu and social menu
[[main]]
    identifier = "home"
    name       = "首页"
    url        = "/"
    weight     = 1
    [main.params]
        icon = "home"

[[main]]
    identifier = "archives"
    name       = "归档"
    url        = "/archives/"
    weight     = 2
    [main.params]
        icon = "archives"

[[main]]
    identifier = "timeline"
    name       = "时间线"
    url        = "/timeline/"
    weight     = 3
    [main.params]
        icon = "archives"

[[main]]
    identifier = "search"
    name       = "搜索"
    url        = "/search/"
    weight     = 4
    [main.params]
        icon = "search"

[[main]]
    identifier = "links"
    name       = "友链"
    url        = "/links/"
    weight     = 5
    [main.params]
        icon = "link"

[[main]]
    identifier = "dm-h3510"
    name       = "DM电机"
    url        = "/dm-motor.html"
    weight     = 6
    [main.params]
        icon = "link"

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/129700"
    weight     = 1

    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "twitter"
    name       = "Twitter"
    url        = "https://twitter.com"
    weight     = 2

    [social.params]
        icon = "brand-twitter"