# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon        = "img/favicon.png"

# Accepted values: "default", "lastmod"
SortBy              = "default"

[footer]
    since      = 2026
    customText = ""

[dateFormat]
    published   = "2006-01-02"
    lastUpdated = "2006-01-02"

[sidebar]
    emoji    = "🤖"
    subtitle = "控制理论 · 嵌入式"
    avatar   = "img/avatar.png"

[article]
    headingAnchor = false
    math          = true
    readingTime   = true
    toc           = true

    [article.license]
        enabled = true
        default = "Licensed under CC BY-NC-SA 4.0"

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[opengraph.twitter]
    site = ""
    card = "summary_large_image"

[colorScheme]
    toggle  = true
    default = "auto"

## Comments
[comments]
    enabled  = false
    provider = "disqus"