# sync-notes.ps1 - Sync Obsidian vault to Hugo blog inbox
param(
    [string]$ConfigFile = ".\sync-config.json"
)

# Load config
$cfg = Get-Content $ConfigFile -Raw -Encoding UTF8 | ConvertFrom-Json
$Source = $cfg.source
$DiaryFolder = $cfg.diary_folder
$MomentsHeading = $cfg.moments_heading
$Target = ".\_inbox"
$MomentsFile = ".\data\moments.yaml"

# Excluded folders
$exclude = @(".obsidian", "Picture", ".git", ".trash", $DiaryFolder)

if (-not (Test-Path $Source)) {
    Write-Host "[ERROR] $Source not found" -ForegroundColor Red
    exit 1
}

# ===== Step 1: Sync MD notes to _inbox =====
if (-not (Test-Path $Target)) {
    New-Item -Path $Target -ItemType Directory -Force | Out-Null
}
Remove-Item "$Target\*" -Recurse -Force -ErrorAction SilentlyContinue
Write-Host "[INBOX] Cleaned" -ForegroundColor Gray

$noteCount = 0
Get-ChildItem -Path $Source -Filter "*.md" -Recurse | ForEach-Object {
    $skip = $false
    foreach ($pat in $exclude) {
        if ($_.FullName -match "\\$pat\\" -or $_.FullName -match "\\$pat$") {
            $skip = $true; break
        }
    }
    if (-not $skip) {
        $rel = $_.FullName.Substring($Source.Length).TrimStart("\")
        $dest = Join-Path $Target $rel
        $destDir = Split-Path $dest -Parent
        if (-not (Test-Path $destDir)) {
            New-Item -Path $destDir -ItemType Directory -Force | Out-Null
        }
        Copy-Item $_.FullName -Destination $dest -Force
        $noteCount++
        Write-Host "  [NOTE] $rel" -ForegroundColor Green
    }
}

# ===== Step 2: Extract moments from diary =====
$diaryPath = Join-Path $Source $DiaryFolder
$moments = @()

if (Test-Path $diaryPath) {
    Write-Host ""
    Write-Host "[MOMENTS] Scanning $DiaryFolder..." -ForegroundColor Magenta

    Get-ChildItem -Path $diaryPath -Filter "*.md" `
    | Sort-Object Name -Descending `
    | ForEach-Object {

        $dateMatch = [regex]::Match($_.BaseName, '^(\d{4}-\d{2}-\d{2})')
        if (-not $dateMatch.Success) { return }
        $day = $dateMatch.Groups[1].Value

        $lines = Get-Content $_.FullName -Encoding UTF8
        $inBlock = $false

        foreach ($line in $lines) {
            $t = $line.Trim()

            if ($t -eq $MomentsHeading) {
                $inBlock = $true
                continue
            }

            if ($inBlock) {
                if ($t.StartsWith("## ") -or $t.StartsWith("# ")) { break }

                $txt = $t.TrimStart('-').Trim()
                if ($txt -ne "") {
                    $moments += @{ date = $day; text = $txt }
                }
            }
        }

        if ($inBlock) {
            Write-Host "  [M] $($_.BaseName)" -ForegroundColor Green
        }
    }
}

# ===== Step 3: Write moments.yaml =====
$yaml = "# Generated by sync-notes.ps1`n"
$yaml += "# Diary: $Source/$DiaryFolder`n"
foreach ($m in $moments) {
    $yaml += "- date: `"$($m.date)`"`n  text: `"$($m.text)`"`n"
}
if ($moments.Count -eq 0) {
    $yaml += "`n"
}

$momentsPath = (Resolve-Path $MomentsFile).Path
[System.IO.File]::WriteAllText($momentsPath, $yaml, [System.Text.UTF8Encoding]::new($false))

# ===== Done =====
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host " Notes  : $noteCount" -ForegroundColor Green
Write-Host " Moments: $($moments.Count)" -ForegroundColor Magenta
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Next: tell me to publish." -ForegroundColor Yellow
