name = "my-blog-greeter"
main = "index.js"
compatibility_date = "2025-06-22"

[vars]
TENCENT_KEY = "C3EBZ-CFS37-HVBX3-HJFP2-CDOSS-PDFI5"
ZHIPU_KEY = "dfa4fa6b5f0549b8869ac68c7c349dc6.zq40GmEKMglpQeOz"

# GLM 用量统计 KV 绑定
[[kv_namespaces]]
binding = "GLM_USAGE"
id = "e863119de9574f489adc7f51adcbff18"
